### Getting all albums
GET http://localhost:8080/albums

### Getting single album 
GET http://localhost:8080/albums/1

### Adding new album
POST http://localhost:8080/albums/addAlbum
Content-Type: application/json

{
    "title": "ham",
    "imageUrl": "https://music.apple.com/us/album/the-writings-on-the-wall/266809606",
    "recordLabel": "Columbia Records",
    "songs":[]
}

### Adding a song to the album
POST http://localhost:8080/albums/1/addSong
Content-Type: application/json

 {
      "title": "My Name Is Ham",
      "link": "google.com",
      "duration": 4,
      "artist": "Destiny's Ham"
}


### Getting all songs
GET http://localhost:8080/songs

### Getting single song
GET http://localhost:8080/songs/3

